const ren=require("./rendering/renderer");
const Mode=require("./constants");
const shapes=require("./shapes");
let pk=new ren(1280, 720);
const ctx=pk._context;
const radians=deg=>deg*(Math.PI/180);
shapes.setRenderer(pk);
pk.state.noFill();
pk.state.stroke("dodgerblue");
pk.state.strokeWeight(8);
shapes.circle(200,200,100);
pk.state.noStroke();
pk.state.colorMode(Mode.HSL);
pk.state.fill(120,100,50);
shapes.rect(200,200,200,200);
pk.draw();
